### ISSUE TITLE
Instead of listing the atom dependencies in the readme try to reference in manifest

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Atom#17]
Readme says we need "language-fsharp" + "autocomplete-plus" package.
Can we define this as dependencies in the package.json?

**Comment by forki** [comment]
like this: https://github.com/hughsk/atom-npm-install/blob/master/package.json#L16 ?

**Comment by Krzysztof-Cieslak** [comment]
As far as I understand, those are dependencies from NPM for node engine, not from APM for Atom plugins. Following part of docs suggest it:  https://atom.io/docs/v0.196.0/hacking-atom-package-modifying-text#add-the-ascii-art

**Comment by forki** [comment]
seems to be an open issue: https://github.com/atom/atom/issues/2412

**Comment by CumpsD** [comment]
Would be very nice, since I don't read all readmes of packages I install and would've missed the autocomplete-plus package

**Comment by Krzysztof-Cieslak** [comment]
`Autocomplete-plus` is now pre-installed part of Atom, we dropped dependency on `language-fsharp` by adding own syntax highlighting. Can be closed.
