### ISSUE TITLE
Intellisense should not work inside string literals

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Atom#29]
![image](https://cloud.githubusercontent.com/assets/873919/7524929/fd4fbf28-f50d-11e4-816e-a1035a32e008.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 0.1.6 https://github.com/fsprojects/FSharp.Atom/commit/c43efbfec50f67de2fa82731f20c95d5dcdfa804
