### ISSUE TITLE
Broken link on https://atom.io/packages/fsharp

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Atom#30]
This one:

![image](https://cloud.githubusercontent.com/assets/873919/7524949/1a08d78a-f50e-11e4-94fb-34b6cf51c268.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in 0.1.6 https://github.com/fsprojects/FSharp.Atom/commit/c43efbfec50f67de2fa82731f20c95d5dcdfa804
