### ISSUE TITLE
Commenting a line does not work

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/FSharp.Atom#40]
In Atom I use `CTRL + /` to comment a line. This comes down to `Editor: Toggle Line Comments`

However, having `language-fsharp`, `FSharp`, `autocomplete-plus` installed, this results in Atom added `/* ..... */` around my code, which doesn't work for F#.

Preferably this comments out each line on it's own with `//`

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 0.1.11

**Comment by CumpsD** [comment]
Verified as working :+1: thanks!
