### ISSUE TITLE
Almost no syntax coloring in light themes

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/FSharp.Atom#46]
![image](https://cloud.githubusercontent.com/assets/873919/7686622/c960511a-fd9f-11e4-9b9e-afe308b27222.png)

**Comment by vasily-kirichenko** [comment]
Actually, colors appear in "Atom Dark" theme only.

**Comment by Krzysztof-Cieslak** [comment]
Syntax highlighting is in scope of https://atom.io/packages/language-fsharp project by @jbtule
